language: julia
sudo: false
julia:
    - 0.7
    - 1.0
os:
    - linux
    - osx

matrix:
  allow_failures:
  - julia: nightly

notifications:
    email: false


script:
  - julia --color=yes --check-bounds=yes -e 'using Pkg; Pkg.add("Test"); Pkg.add("Random"); Pkg.update(); Pkg.test("Threadings", coverage=true)'


after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Threadings")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
