language: julia
sudo: false
julia:
    - 0.6
os:
    - linux
    - osx

matrix:
  allow_failures:
  - julia: nightly

notifications:
    email: false

script:
  - export JL_PKG=Threadings
  - julia --color=yes -e "Pkg.clone(pwd()); Pkg.build(\"${JL_PKG}\"); Pkg.test(\"${JL_PKG}\", coverage=true);"

after_success:
  - julia -e 'cd(Pkg.dir("Threadings")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
